//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldEdge_CRUD_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessInfo
    {
        public int Orginization { get; set; }
        public string Business { get; set; }
        public string Date_Recieved { get; set; }
        public string Amount { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
    }
}
